"""
Skill base class — the atomic LLM interaction unit.

Each Skill is an independent LLM call unit:
  input schema -> build_prompt -> LLM call -> parse_output -> output schema

Inspired by OpenClaw's SKILL.md declarative pattern, combined with
Python dataclass for type safety.
"""
from __future__ import annotations

import json
import logging
import re
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger("inkoctobot.agents.base_skill")


@dataclass
class SkillMeta:
    """Skill metadata, corresponding to SKILL.md frontmatter."""
    name: str                                     # unique id, e.g. "consistency_check"
    display_name: str                             # display name, e.g. "一致性检查"
    description: str                              # functional description
    version: str = "1.0.0"
    input_schema: dict[str, Any] = field(default_factory=dict)    # JSON Schema
    output_schema: dict[str, Any] = field(default_factory=dict)   # JSON Schema
    model_role: str = "default"                   # maps to models.yaml role
    max_tokens: int = 4096
    temperature: float = 0.7
    tags: list[str] = field(default_factory=list)
    learnable: bool = False                       # True if generated by self-learning
    permissions: list[str] = field(default_factory=list)


class BaseSkill(ABC):
    """
    Abstract base for all Skills.

    Every skill.py must export a ``Skill`` class inheriting from this.
    """

    @abstractmethod
    def meta(self) -> SkillMeta:
        """Return skill metadata."""
        ...

    @abstractmethod
    async def build_prompt(self, inputs: dict[str, Any]) -> str:
        """Build the LLM prompt from structured inputs."""
        ...

    @abstractmethod
    async def parse_output(self, raw: str) -> dict[str, Any]:
        """Parse raw LLM text into structured output."""
        ...

    async def execute(
        self,
        inputs: dict[str, Any],
        model_router: Any,
    ) -> dict[str, Any]:
        """Standard execution flow: build_prompt -> LLM call -> parse_output."""
        prompt = await self.build_prompt(inputs)
        raw = await model_router.invoke(
            role=self.meta().model_role,
            prompt=prompt,
            max_tokens=self.meta().max_tokens,
            temperature=self.meta().temperature,
        )
        return await self.parse_output(raw)

    async def execute_with_messages(
        self,
        inputs: dict[str, Any],
        model_router: Any,
    ) -> dict[str, Any]:
        """Execute using the full ModelRouter.generate() message-based API."""
        from models.base import LLMMessage
        prompt = await self.build_prompt(inputs)
        meta = self.meta()
        messages = [
            LLMMessage(role="system", content=meta.description),
            LLMMessage(role="user", content=prompt),
        ]
        resp = await model_router.generate(
            agent_role=meta.model_role,
            messages=messages,
            temperature=meta.temperature,
            max_tokens=meta.max_tokens,
        )
        return await self.parse_output(resp.content)

    # ── Helpers ──────────────────────────────────────────────────

    @staticmethod
    def extract_json(text: str) -> Any:
        """Extract the first JSON object or array from LLM output."""
        for pattern in [r"```json\s*([\s\S]*?)```", r"```\s*([\s\S]*?)```"]:
            m = re.search(pattern, text)
            if m:
                try:
                    return json.loads(m.group(1))
                except json.JSONDecodeError:
                    continue
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            return None

    def validate_inputs(self, inputs: dict[str, Any]) -> bool:
        """Validate inputs against input_schema (if jsonschema available)."""
        schema = self.meta().input_schema
        if not schema:
            return True
        try:
            import jsonschema
            jsonschema.validate(inputs, schema)
            return True
        except ImportError:
            return True
        except jsonschema.ValidationError as e:
            logger.warning("Input validation failed: %s", e.message)
            return False

    def validate_outputs(self, outputs: dict[str, Any]) -> bool:
        """Validate outputs against output_schema (if jsonschema available)."""
        schema = self.meta().output_schema
        if not schema:
            return True
        try:
            import jsonschema
            jsonschema.validate(outputs, schema)
            return True
        except ImportError:
            return True
        except jsonschema.ValidationError as e:
            logger.warning("Output validation failed: %s", e.message)
            return False
